# Generated by Django 3.1 on 2021-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop', '0002_auto_20210423_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя актера')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('order', 'product')},
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название фильма')),
                ('actors', models.ManyToManyField(to='supershop.Actor')),
            ],
        ),
    ]
